services:
  qwen3tts:
    build: .
    restart: unless-stopped
    ports:
      - "8335:8335"
    volumes:
      - qwen3tts-learn_hf-cache:/root/.cache/huggingface
      - ./DaveSample.m4a:/app/DaveSample.m4a
      - ./claire.mp3:/app/claire.mp3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  qwen3tts-learn_hf-cache:
    external: true
